version: 2.1
orbs:
  elixir: membraneframework/elixir@1
  win: circleci/windows@4.1

jobs:
  windows_test:
    executor: 
      name: win/default
      size: medium
      shell: cmd.exe

    steps: 
      - checkout

      - restore_cache:
          keys:
            [choco-cache]

      - run:
          name: Install Elixir
          command: choco install -y erlang elixir

      - save_cache:
          key: choco-cache
          paths:
            - C:\Users\circleci\AppData\Local\Temp

      - run: 
          name: Get dependencies
          command: |
            refreshenv && C:\ProgramData\chocolatey\lib\Elixir\tools\bin\mix local.hex --force && C:\ProgramData\chocolatey\lib\Elixir\tools\bin\mix deps.get

      - run: 
          name: Run all tests
          command: |
            refreshenv && C:\ProgramData\chocolatey\lib\Elixir\tools\bin\mix test --warnings-as-errors

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
      - elixir/test:
          filters:
            <<: *filters
      - elixir/lint:
          filters:
            <<: *filters
      - windows_test:
          filters:
            <<: *filters
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
            - windows_test
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/

