version: 2.0
jobs:
  test:
    docker:
      - image: membraneframeworklabs/docker_membrane:latest
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout
      - run: mix deps.get
      - run: mix compile --force --warnings-as-errors
      - run: mix test

  lint:
    docker:
      - image: membraneframeworklabs/docker_membrane:latest
        environment:
          MIX_ENV: dev

    working_directory: ~/app

    steps:
      - checkout
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile
      - run: mix credo
      - run: mix docs && mix docs 2>&1 | (! grep -q "warning:")

workflows:
  version: 2
  build:
    jobs:
      - test
      - lint
